services:
  mariadb:
    image: hjben/mariadb:10.5
    hostname: mariadb
    container_name: mariadb
    privileged: true
    ports:
      - 3306:3306
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /Users/Shared/workspace/docker-ws/maria-data:/var/lib/mysql 
    environment:
      MARIADB_ROOT_PASSWORD: mariadb
    networks:
      hadoop-cluster:
        ipv4_address: 10.0.2.2
    extra_hosts:
      - "mariadb:10.0.2.2"
      - "master:10.0.2.3"
      - "kafka-server:10.0.2.7"
      - "nifi:10.0.2.8"
      - "slave3:10.0.2.6"
      - "slave2:10.0.2.5"
      - "slave1:10.0.2.4"

  master:
    image: hjben/hadoop-eco:3.3.0
    hostname: master
    container_name: master
    privileged: true
    ports:
      - 8088:8088
      - 9870:9870
      - 8042:8042
      - 10000:10000
      - 10002:10002
      - 16010:16010
      - 9000:9000
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /tmp/hadoop:/data/hadoop
      - /tmp/hadoop_logs:/usr/local/hadoop/logs
      - /tmp/hbase_logs/master:/usr/local/hbase/logs
      - /tmp/hive_logs:/usr/local/hive/logs
      - /tmp/sqoop_logs:/usr/local/sqoop/logs
    networks:
      hadoop-cluster:
        ipv4_address: 10.0.2.3
    extra_hosts:
      - "mariadb:10.0.2.2"
      - "master:10.0.2.3"
      - "kafka-server:10.0.2.7"
      - "nifi:10.0.2.8"
      - "slave3:10.0.2.6"
      - "slave2:10.0.2.5"
      - "slave1:10.0.2.4"

  slave3:
    image: hjben/hbase:1.6.0-hadoop3.3.0
    hostname: slave3
    container_name: slave3
    privileged: true
    ports:
      - 16032:16030
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /tmp/hbase_logs/slave3:/usr/local/hbase/logs
    networks:
      hadoop-cluster:
        ipv4_address: 10.0.2.6
    extra_hosts:
      - "mariadb:10.0.2.2"
      - "master:10.0.2.3"
      - "kafka-server:10.0.2.7"
      - "nifi:10.0.2.8"
      - "slave3:10.0.2.6"
      - "slave2:10.0.2.5"
      - "slave1:10.0.2.4"

  slave2:
    image: hjben/hbase:1.6.0-hadoop3.3.0
    hostname: slave2
    container_name: slave2
    privileged: true
    ports:
      - 16031:16030
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /tmp/hbase_logs/slave2:/usr/local/hbase/logs
    networks:
      hadoop-cluster:
        ipv4_address: 10.0.2.5
    extra_hosts:
      - "mariadb:10.0.2.2"
      - "master:10.0.2.3"
      - "kafka-server:10.0.2.7"
      - "nifi:10.0.2.8"
      - "slave3:10.0.2.6"
      - "slave2:10.0.2.5"
      - "slave1:10.0.2.4"

  slave1:
    image: hjben/hbase:1.6.0-hadoop3.3.0
    hostname: slave1
    container_name: slave1
    privileged: true
    ports:
      - 16030:16030
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /tmp/hbase_logs/slave1:/usr/local/hbase/logs
    networks:
      hadoop-cluster:
        ipv4_address: 10.0.2.4
    extra_hosts:
      - "mariadb:10.0.2.2"
      - "master:10.0.2.3"
      - "kafka-server:10.0.2.7"
      - "nifi:10.0.2.8"
      - "slave3:10.0.2.6"
      - "slave2:10.0.2.5"
      - "slave1:10.0.2.4"

  kafka-server:
    image: bitnami/kafka:latest
    hostname: kafka-server
    container_name: kafka-server-hadoop
    privileged: true
    ports:
      - 9092:9092
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /tmp/kafka_log:/usr/local/kafka/logs
    environment:
      ALLOW_PLAINTEXT_LISTENER: "true"
    networks:
      hadoop-cluster:
        ipv4_address: 10.0.2.7
    extra_hosts:
      - "mariadb:10.0.2.2"
      - "master:10.0.2.3"
      - "kafka-server:10.0.2.7"
      - "nifi:10.0.2.8"
      - "slave3:10.0.2.6"
      - "slave2:10.0.2.5"
      - "slave1:10.0.2.4"

  nifi:
    image: bck_img_nifi:latest
    hostname: nifi
    container_name: nifi-hadoop
    privileged: true
    ports:
      - 8443:8443
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /tmp/nifi_log:/usr/local/nifi/logs
      - /opt/nifi/drivers:/opt/nifi/nifi-ext-lib  
    networks:
      hadoop-cluster:
        ipv4_address: 10.0.2.8
    extra_hosts:
      - "mariadb:10.0.2.2"
      - "master:10.0.2.3"
      - "kafka-server:10.0.2.7"
      - "nifi:10.0.2.8"
      - "slave3:10.0.2.6"
      - "slave2:10.0.2.5"
      - "slave1:10.0.2.4"

networks:
 hadoop-cluster:
  ipam:
   driver: default
   config:
   - subnet: 10.0.2.0/24
